### ISSUE TITLE
Entry points folder not updating with route changes

### ISSUE THREAD

**Issue by layout-ch** [florian-lefebvre/astro-i18n-test#18] opened 2024-04-16 17:37 UTC
The entry points folder generated by the i18n package within the .astro directory does not update to reflect changes made to route names. This leads to errors both locally and when pushing to platforms like Netlify if routes are changed (e.g., from uppercase to lowercase), as the entry points folder retains references to the old route names. While manually deleting the folder locally resolves the issue, this is not a viable solution for platforms like Netlify where manual deletion is not possible. Ideally, the entry points folder should automatically update to reflect route changes without requiring manual intervention.

![image](https://github.com/astrolicious/i18n/assets/164497867/d5a3f671-e8f2-4a6e-84a2-003efe05949c)

**Comment by florian-lefebvre** [comment] 2024-04-16 17:47
I need to investigate but that may be related to relative links. Basically, since contents are copied over, I have to rewrite all relative paths and that may cause this issue.

**Comment by florian-lefebvre** [comment] 2024-05-05 12:53
I never managed to reproduce it, closing for now. Feel free to reopen with more info if you still encounter it

**Closed as not planned by florian-lefebvre** 2024-05-05 12:53 UTC
Labels: bug, question
